name: Build and Push Docker Images

on:
  push:
    branches:
      - Docker  # Specify the branch that triggers this workflow

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push images
    - name: Build and Push AuthDB
      uses: docker/build-push-action@v4
      with:
        context: ./Databases/Auth
        push: true
        tags: chris2750/mtogo-authdb:latest

    - name: Build and Push OrderDB
      uses: docker/build-push-action@v4
      with:
        context: ./Databases/Order
        push: true
        tags: chris2750/mtogo-orderdb:latest

    - name: Build and Push RestaurantDB
      uses: docker/build-push-action@v4
      with:
        context: ./Databases/Restaurant
        push: true
        tags: chris2750/mtogo-restaurantdb:latest

    - name: Build and Push ReviewDB
      uses: docker/build-push-action@v4
      with:
        context: ./Databases/Review
        push: true
        tags: chris2750/mtogo-reviewdb:latest

    - name: Build and Push ShoppingCartAPI
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./MTOGO.Services.ShoppingCartAPI/Dockerfile
        push: true
        tags: chris2750/mtogo-shoppingcartapi:latest

    - name: Build and Push OrderAPI
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./MTOGO.Services.OrderAPI/Dockerfile
        push: true
        tags: chris2750/mtogo-orderapi:latest

    - name: Build and Push Gateway
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./MTOGO.GatewaySolution/Dockerfile
        push: true
        tags: chris2750/mtogo-gateway:latest

    - name: Build and Push AuthAPI
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./MTOGO.Services.AuthAPI/Dockerfile
        push: true
        tags: chris2750/mtogo-authapi:latest

    - name: Build and Push RestaurantAPI
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./MTOGO.Services.RestaurantAPI/Dockerfile
        push: true
        tags: chris2750/mtogo-restaurantapi:latest

    - name: Build and Push ReviewAPI
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./MTOGO.Services.ReviewAPI/Dockerfile
        push: true
        tags: chris2750/mtogo-reviewapi:latest
