name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
          - 15672:15672

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Restore dependencies for individual projects
      - name: Restore dependencies
        run: |
          dotnet restore ./MTOGO.UnitTests/MTOGO.UnitTests.csproj
          dotnet restore ./MTOGO.IntegrationTests/MTOGO.IntegrationTests.csproj

      # Build individual test projects
      - name: Build projects
        run: |
          dotnet build ./MTOGO.UnitTests/MTOGO.UnitTests.csproj --no-restore --configuration Release
          dotnet build ./MTOGO.IntegrationTests/MTOGO.IntegrationTests.csproj --no-restore --configuration Release

      # Run Unit Tests
      - name: Run Unit Tests
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
        run: dotnet test ./MTOGO.UnitTests/MTOGO.UnitTests.csproj --no-build --configuration Release

      # Run Integration Tests
      - name: Run Integration Tests
        env:
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          RABBITMQ_HOST: localhost
          RABBITMQ_PORT: 5672
        run: dotnet test ./MTOGO.IntegrationTests/MTOGO.IntegrationTests.csproj --no-build --configuration Release
